# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "napjoseph"
license = "MIT"
licenselink = "https://github.com/napjoseph/napjoseph-gohugo-theme/blob/master/LICENSE"
description = "A gohugo theme for napjose.ph"
homepage = "https://napjose.ph/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Nap Joseph Calub"
  homepage = "https://napjose.ph/"
