title = "fabri de magia"
baseURL = "https://napjose.ph/napjoseph-gohugo-theme"
languageCode = "en-us"
theme = "napjoseph-gohugo-theme"
themesDir = "../.."

googleAnalytics = ""

[params]
  description = "the makers of magic"
  recentPostsToShow = 5
