title = "fabri de magia"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "napjoseph-gohugo-theme"
themesDir = "../.."

googleAnalytics = ""

[params]
  description = "Any sufficiently advanced technology is indistinguishable from magic."
